/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DoarRouteImport } from './routes/doar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BazarRouteImport } from './routes/bazar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos_.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos_.$slug'
import { Route as DoarObrigadoRouteImport } from './routes/doar.obrigado'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTransparenciaRouteImport } from './routes/admin.transparencia'
import { Route as AdminProjetosRouteImport } from './routes/admin.projetos'
import { Route as AdminParceirosRouteImport } from './routes/admin.parceiros'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminDoacoesRouteImport } from './routes/admin.doacoes'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as ApiPublicDonationsWebhookRouteImport } from './routes/api/public/donations/webhook'
import { Route as ApiPublicDonationsStatusRouteImport } from './routes/api/public/donations/status'
import { Route as ApiPublicDonationsCreateRouteImport } from './routes/api/public/donations/create'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarRoute = DoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BazarRoute = BazarRouteImport.update({
  id: '/bazar',
  path: '/bazar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjetosRoute,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos_/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos_/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarObrigadoRoute = DoarObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => DoarRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransparenciaRoute = AdminTransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosRoute = AdminProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParceirosRoute = AdminParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoacoesRoute = AdminDoacoesRouteImport.update({
  id: '/doacoes',
  path: '/doacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicDonationsWebhookRoute =
  ApiPublicDonationsWebhookRouteImport.update({
    id: '/api/public/donations/webhook',
    path: '/api/public/donations/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDonationsStatusRoute =
  ApiPublicDonationsStatusRouteImport.update({
    id: '/api/public/donations/status',
    path: '/api/public/donations/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDonationsCreateRoute =
  ApiPublicDonationsCreateRouteImport.update({
    id: '/api/public/donations/create',
    path: '/api/public/donations/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/bazar': typeof BazarRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/doacoes': typeof AdminDoacoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/transparencia': typeof AdminTransparenciaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doar/obrigado': typeof DoarObrigadoRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/api/public/donations/create': typeof ApiPublicDonationsCreateRoute
  '/api/public/donations/status': typeof ApiPublicDonationsStatusRoute
  '/api/public/donations/webhook': typeof ApiPublicDonationsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bazar': typeof BazarRoute
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/doacoes': typeof AdminDoacoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/transparencia': typeof AdminTransparenciaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doar/obrigado': typeof DoarObrigadoRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/api/public/donations/create': typeof ApiPublicDonationsCreateRoute
  '/api/public/donations/status': typeof ApiPublicDonationsStatusRoute
  '/api/public/donations/webhook': typeof ApiPublicDonationsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/bazar': typeof BazarRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/transparencia': typeof TransparenciaRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/doacoes': typeof AdminDoacoesRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/projetos': typeof AdminProjetosRoute
  '/admin/transparencia': typeof AdminTransparenciaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/doar/obrigado': typeof DoarObrigadoRoute
  '/eventos_/$slug': typeof EventosSlugRoute
  '/projetos_/$slug': typeof ProjetosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/api/public/donations/create': typeof ApiPublicDonationsCreateRoute
  '/api/public/donations/status': typeof ApiPublicDonationsStatusRoute
  '/api/public/donations/webhook': typeof ApiPublicDonationsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/bazar'
    | '/blog'
    | '/contato'
    | '/doar'
    | '/eventos'
    | '/parceiros'
    | '/projetos'
    | '/quem-somos'
    | '/transparencia'
    | '/admin/blog'
    | '/admin/doacoes'
    | '/admin/emails'
    | '/admin/eventos'
    | '/admin/integracoes'
    | '/admin/parceiros'
    | '/admin/projetos'
    | '/admin/transparencia'
    | '/admin/usuarios'
    | '/blog/$slug'
    | '/doar/obrigado'
    | '/eventos/$slug'
    | '/projetos/$slug'
    | '/admin/'
    | '/blog/'
    | '/eventos/'
    | '/projetos/'
    | '/api/public/donations/create'
    | '/api/public/donations/status'
    | '/api/public/donations/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/bazar'
    | '/contato'
    | '/doar'
    | '/parceiros'
    | '/quem-somos'
    | '/transparencia'
    | '/admin/blog'
    | '/admin/doacoes'
    | '/admin/emails'
    | '/admin/eventos'
    | '/admin/integracoes'
    | '/admin/parceiros'
    | '/admin/projetos'
    | '/admin/transparencia'
    | '/admin/usuarios'
    | '/blog/$slug'
    | '/doar/obrigado'
    | '/eventos/$slug'
    | '/projetos/$slug'
    | '/admin'
    | '/blog'
    | '/eventos'
    | '/projetos'
    | '/api/public/donations/create'
    | '/api/public/donations/status'
    | '/api/public/donations/webhook'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/bazar'
    | '/blog'
    | '/contato'
    | '/doar'
    | '/eventos'
    | '/parceiros'
    | '/projetos'
    | '/quem-somos'
    | '/transparencia'
    | '/admin/blog'
    | '/admin/doacoes'
    | '/admin/emails'
    | '/admin/eventos'
    | '/admin/integracoes'
    | '/admin/parceiros'
    | '/admin/projetos'
    | '/admin/transparencia'
    | '/admin/usuarios'
    | '/blog_/$slug'
    | '/doar/obrigado'
    | '/eventos_/$slug'
    | '/projetos_/$slug'
    | '/admin/'
    | '/blog/'
    | '/eventos/'
    | '/projetos/'
    | '/api/public/donations/create'
    | '/api/public/donations/status'
    | '/api/public/donations/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  BazarRoute: typeof BazarRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DoarRoute: typeof DoarRouteWithChildren
  EventosRoute: typeof EventosRouteWithChildren
  ParceirosRoute: typeof ParceirosRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  QuemSomosRoute: typeof QuemSomosRoute
  TransparenciaRoute: typeof TransparenciaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EventosSlugRoute: typeof EventosSlugRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ApiPublicDonationsCreateRoute: typeof ApiPublicDonationsCreateRoute
  ApiPublicDonationsStatusRoute: typeof ApiPublicDonationsStatusRoute
  ApiPublicDonationsWebhookRoute: typeof ApiPublicDonationsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar': {
      id: '/doar'
      path: '/doar'
      fullPath: '/doar'
      preLoaderRoute: typeof DoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazar': {
      id: '/bazar'
      path: '/bazar'
      fullPath: '/bazar'
      preLoaderRoute: typeof BazarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof EventosRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projetos_/$slug': {
      id: '/projetos_/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos_/$slug': {
      id: '/eventos_/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar/obrigado': {
      id: '/doar/obrigado'
      path: '/obrigado'
      fullPath: '/doar/obrigado'
      preLoaderRoute: typeof DoarObrigadoRouteImport
      parentRoute: typeof DoarRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transparencia': {
      id: '/admin/transparencia'
      path: '/transparencia'
      fullPath: '/admin/transparencia'
      preLoaderRoute: typeof AdminTransparenciaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos': {
      id: '/admin/projetos'
      path: '/projetos'
      fullPath: '/admin/projetos'
      preLoaderRoute: typeof AdminProjetosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parceiros': {
      id: '/admin/parceiros'
      path: '/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AdminParceirosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doacoes': {
      id: '/admin/doacoes'
      path: '/doacoes'
      fullPath: '/admin/doacoes'
      preLoaderRoute: typeof AdminDoacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/donations/webhook': {
      id: '/api/public/donations/webhook'
      path: '/api/public/donations/webhook'
      fullPath: '/api/public/donations/webhook'
      preLoaderRoute: typeof ApiPublicDonationsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/donations/status': {
      id: '/api/public/donations/status'
      path: '/api/public/donations/status'
      fullPath: '/api/public/donations/status'
      preLoaderRoute: typeof ApiPublicDonationsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/donations/create': {
      id: '/api/public/donations/create'
      path: '/api/public/donations/create'
      fullPath: '/api/public/donations/create'
      preLoaderRoute: typeof ApiPublicDonationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDoacoesRoute: typeof AdminDoacoesRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminParceirosRoute: typeof AdminParceirosRoute
  AdminProjetosRoute: typeof AdminProjetosRoute
  AdminTransparenciaRoute: typeof AdminTransparenciaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminDoacoesRoute: AdminDoacoesRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminParceirosRoute: AdminParceirosRoute,
  AdminProjetosRoute: AdminProjetosRoute,
  AdminTransparenciaRoute: AdminTransparenciaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DoarRouteChildren {
  DoarObrigadoRoute: typeof DoarObrigadoRoute
}

const DoarRouteChildren: DoarRouteChildren = {
  DoarObrigadoRoute: DoarObrigadoRoute,
}

const DoarRouteWithChildren = DoarRoute._addFileChildren(DoarRouteChildren)

interface EventosRouteChildren {
  EventosIndexRoute: typeof EventosIndexRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosIndexRoute: EventosIndexRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

interface ProjetosRouteChildren {
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosIndexRoute: ProjetosIndexRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  BazarRoute: BazarRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DoarRoute: DoarRouteWithChildren,
  EventosRoute: EventosRouteWithChildren,
  ParceirosRoute: ParceirosRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  QuemSomosRoute: QuemSomosRoute,
  TransparenciaRoute: TransparenciaRoute,
  BlogSlugRoute: BlogSlugRoute,
  EventosSlugRoute: EventosSlugRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ApiPublicDonationsCreateRoute: ApiPublicDonationsCreateRoute,
  ApiPublicDonationsStatusRoute: ApiPublicDonationsStatusRoute,
  ApiPublicDonationsWebhookRoute: ApiPublicDonationsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
